### ISSUE TITLE
[Front end] Migrate all components to this repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/design#5]
This repo will house the future design system for design.opensauced.pizza. This will copy all components from design-insights.opensauced.pizza

All [components from the insights repo](https://github.com/open-sauced/insights/tree/beta/components) need to be moved here. The component should be UI only and not include logic.  i.e. https://github.com/open-sauced/insights/issues/197 - Don't do this.

![Screen Shot 2022-08-29 at 12 57 29 PM](https://user-images.githubusercontent.com/5713670/187287196-b1014389-7352-4d9c-976b-283105d75794.png)

This work is needed to ship the contributor.info project

https://github.com/open-sauced/insights/issues/132

**Comment by SunGoldTech** [comment]
A quick question @bdougie, Am I to rip off the logic in the app components as well? or just the Stories?

**Comment by bdougie** [comment]
no logic. This should be reusable as components in a new app.
