### ISSUE TITLE
Docs: clean up project instructions and setup in README

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/design#8]
### Describe the bug

The README has instructions for the insights project, some of which don't apply to the design system

### Steps to reproduce

See README

### Affected services

design.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by janie-lee-developer** [comment]
@brandonroberts Would you mind helping me understand which section of the readme.md file I need to update? The 2 links about atomic design was helpful. Some instructions don't apply to the design system?

**Comment by brandonroberts** [comment]
@janie-lee-developer Sure.

- The design system information is good and can remain
- The `Local Development` section should include the instructions on running Storybook
- Add a small description about the different folders in the design system as an overview
- Update the description of this repo from `insights.opensauced.pizza` to the deployed URL

**Comment by janie-lee-developer** [comment]
@brandonroberts  Thank you so much Brandon!
If you don't mind, could you help me understand the last comment, again? 
_Update the description of this repo from insights.opensauced.pizza to the deployed URL_
Thank you so much in advance!
