### ISSUE TITLE
Feature: Remove everything except atoms for now

### ISSUE THREAD

**Issue by bdougie** [open-sauced/design#9]
### Type of feature

🍕 Feature

### Current behavior

<img width="223" alt="Screen Shot 2022-11-17 at 9 44 16 AM" src="https://user-images.githubusercontent.com/5713670/202519187-e21941d0-5876-467e-948b-a0a83aae04d8.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
.take

**Comment by shamimbinnur** [comment]
@bdougie  I can see we do not have any story left in the design system except the atoms. Is this issue meant to remove everything (ex. pages, layout, etc) besides stories in the codebase?

From the storybook
![Screenshot 2023-03-18 at 2 00 20 PM](https://user-images.githubusercontent.com/48399373/226093423-5712c93c-f2fa-4711-996c-492a9b9cccb0.png)

From code editor.
<img width="372" alt="Screenshot 2023-03-18 at 2 01 30 PM" src="https://user-images.githubusercontent.com/48399373/226093428-57feec83-a34d-43bb-9273-dc608bdb24d8.png">

**Comment by bdougie** [comment]
Correct, but also all logic too. Some components have auth wrappers.

The next step is adding components, which are molecules
